### ISSUE TITLE
create pull request template

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/evently#4]

**Comment by mosespace** [comment]
Hi, @HassanBahati I can do this according to the likes; welcome back from the flutter forward event 👍

**Comment by HassanBahati** [comment]
> Hi, @HassanBahati I can do this according to the likes; welcome back from the flutter forward event +1

thank you :smile: am surprised how you know i attended it :laughing:

**Comment by HassanBahati** [comment]
this can be inspired by https://github.com/OSCA-Kampala-Chapter/react-ui/pull/63 which you actually solved..

**Comment by mosespace** [comment]
Just because I was there it's the reason as to why I saw you 😂

**Comment by mosespace** [comment]
> this can be inspired by [OSCA-Kampala-Chapter/react-ui#63](https://github.com/OSCA-Kampala-Chapter/react-ui/pull/63) which you actually solved..

Aright Ago work on it 😋

**Comment by HassanBahati** [comment]
> Just because I was there it's the reason as to why I saw you joy

why didnt you halla :rofl:

**Comment by mosespace** [comment]
> > Just because I was there it's the reason as to why I saw you joy
> 
> why didnt you halla 🤣
>
Manh, next time i will 😂
