### ISSUE TITLE
set up prettier

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/evently#5]

**Comment by mosespace** [comment]
@HassanBahati I can work on `this!` 😊

**Comment by HassanBahati** [comment]
yah sure :rocket: go for it @mosespace

**Comment by mosespace** [comment]
Now it is also easier to disable prettier in a project just as simple as can also disabling the extension for your current workspace. I think this needs to be added to the documentation part! @HassanBahati  what do you think?
> Go to your `extensions` and hit the gear icon on Prettier, then select "Disable (Workspace)"
![image](https://user-images.githubusercontent.com/111237257/226299516-6b809e86-3c9b-423a-b0e7-824e1533cac9.png)

**Comment by HassanBahati** [comment]
yah sure the vscode extension is perfect for local development and people that use vscode...but other contributors they may not be using vscode so we need to install `prettier` into the project so that the files can still be formatted.

this guide maybe of help
https://dev-yakuza.posstree.com/en/react/nextjs/prettier/
